### ISSUE TITLE
Docker image to use for LaTeX processing

### ISSUE THREAD

**Issue by yegor256** [vryazanov/web-latex-compiler#1]
You can use this image: https://github.com/yegor256/dockers/tree/master/papers

It's in Docker hub: https://hub.docker.com/r/yegor256/papers

This is how you compile LaTeX content (if the name of the file is `article.tex`):

```
$ docker run -it --rm yegor256/papers pdflatex article.tex -shell-escape -halt-on-error -interaction=errorstopmode
```

Should work.

**Comment by vryazanov** [comment]
@yegor256 what's the average time of compiling your latex docs? just I've checked a few simple examples and it worked pretty fast synchronously. So I think the first simple working version will work without the queue (I'm going to deploy tomorrow)
