### ISSUE TITLE
Define UI Requirements

### ISSUE THREAD

**Issue by pablopaul** [vryazanov/web-latex-compiler#2]
Please provide UI requirements to make contribution in UI respects easy.

**Comment by vryazanov** [comment]
@pablopaul actually I don't know how it will be. I will come to UI when design of back-end part is done. So if you have suggestions, you are welcome.

**Comment by pablopaul** [comment]
Can you define the functional requirements for the Frontend?

**Comment by vryazanov** [comment]
@pablopaul requirements are quite simple: user should have ability to upload latex file and its assets (images and so on). Frontend sends files to backend and gets some unique ID. and then using this ID it's waiting while pdf file is generated. I guess this is how it should be. wdyt?

**Comment by vryazanov** [comment]
I digged into the idea deeper and found that currently frontend is not needed. If anything I'll let you know, thanks for you attention!
